# Main entrypoint of the workflow for GROMACS MD Simulations.
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html

# load configuration
# -----------------------------------------------------
configfile: "config/config.yaml"

# load rules
# -----------------------------------------------------
include: "rules/common.smk"
include: "rules/prepare_topology.smk"
include: "rules/energy_minimize.smk"
include: "rules/equilibrate.smk"
include: "rules/production.smk"
include: "rules/analysis.smk"

# optional messages, log and error handling
# -----------------------------------------------------
onstart:
    print("\n--- GROMACS MD Simulation Workflow Started ---\n")

onsuccess:
    print("\n--- Workflow finished successfully! ---\n")

onerror:
    print("\n--- An error occurred in the workflow! ---\n")

# target rules
# -----------------------------------------------------
rule all:
    input:
        expand(
            "results/{sample}/analysis/energy.xvg",
            sample=samples.index,
        ),
    default_target: True
