# Main entrypoint of the workflow for GROMACS MD Simulations.
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html

# load configuration
# -----------------------------------------------------
configfile: "config/config.yaml"

# load rules and common functions
# -----------------------------------------------------
include: "rules/common.smk"
include: "rules/prepare_topology.smk"
include: "rules/energy_minimize.smk"
include: "rules/equilibrate.smk"
include: "rules/production.smk"
include: "rules/analysis.smk"

# optional messages, log and error handling
# ------------------------------------------------ ----
onstart:
    print("\n--- GROMACS MD Simulation Workflow Started ---\n")

onsuccess:
    print("\n--- Workflow finished successfully! ---\n")

onerror:
    print("\n--- An error occurred in the workflow! ---\n")

# target rules
# Generate output for all production replicates
def get_all_outputs():
    outputs = []
    for sample in samples.index:
        n_replicates = get_prod_replicates(sample)
        for rep in range(1, n_replicates + 1):
            #outputs.append(f"results/{sample}/analysis/rep{rep}/energy.xvg")
            outputs.append(f"results/{sample}/production/rep{rep}/{sample}_prod.gro")
    return outputs

rule all:
    input:
        get_all_outputs(),
